ro.build.type=user
ro.build.tags=release-keys
ro.build.flavor=automotive_1024-user
ro.build.fingerprint=generic/automotive_1024/automotive_1024:14/UD1A.fake/000000:user/release-keys
ro.product.manufacturer=Generic
ro.product.brand=generic
ro.product.model=Automotive 1024
ro.product.name=automotive_1024
ro.product.device=automotive_1024
ro.vendor.build.type=user
ro.vendor.build.tags=release-keys
ro.vendor.build.fingerprint=generic/automotive_1024/automotive_1024:14/UD1A.fake/000000:user/release-keys
ro.vendor.build.security_patch=2024-09-05
ro.bootimage.build.fingerprint=generic/automotive_1024/automotive_1024:14/UD1A.fake/000000:user/release-keys
ro.product.cpu.abilist=x86_64,x86,arm64-v8a,armeabi-v7a
ro.product.cpu.abilist32=x86,armeabi-v7a
ro.product.cpu.abilist64=x86_64,arm64-v8a
ro.dalvik.vm.native.bridge=libndk_translation.so
ro.enable.native.bridge.exec=1
ro.enable.native.bridge.exec64=1
ro.dalvik.vm.isa.arm=x86
ro.dalvik.vm.isa.arm64=x86_64
ro.zygote=zygote64_32
persist.sys.nativebridge=1
