ro.build.type=user
ro.build.tags=release-keys
ro.build.flavor=wearos_square-user
ro.build.fingerprint=google/wearos_square/wearos_square:14/UD1A.fake/000000:user/release-keys
ro.product.manufacturer=Google
ro.product.brand=google
ro.product.model=Wearos Square
ro.product.name=wearos_square
ro.product.device=wearos_square
ro.vendor.build.type=user
ro.vendor.build.tags=release-keys
ro.vendor.build.fingerprint=google/wearos_square/wearos_square:14/UD1A.fake/000000:user/release-keys
ro.vendor.build.security_patch=2024-09-05
ro.bootimage.build.fingerprint=google/wearos_square/wearos_square:14/UD1A.fake/000000:user/release-keys
ro.product.cpu.abilist=x86_64,x86,arm64-v8a,armeabi-v7a
ro.product.cpu.abilist32=x86,armeabi-v7a
ro.product.cpu.abilist64=x86_64,arm64-v8a
ro.dalvik.vm.native.bridge=libndk_translation.so
ro.enable.native.bridge.exec=1
ro.enable.native.bridge.exec64=1
ro.dalvik.vm.isa.arm=x86
ro.dalvik.vm.isa.arm64=x86_64
ro.zygote=zygote64_32
persist.sys.nativebridge=1
